### ISSUE TITLE
How is the LunchCoin

### ISSUE THREAD

**Issue by zecixx** [technion/lunchcoin#1]
Hello technion,

I am writing to you to ask how is the lunchcoin project going? I was talking to a co worker, it went something like this.

"If I get lunch, and you paypall me, and then you get lunch and I paypall you, and I get lunch, and you get lunch and I get lunch and you get lunch do we really owe each other?" 
"No, but it could get difficult to keep tracking so its best to just pay anyway"
"What if there was a blockchain that kept track for you"
"Well that would be cool, it would have to be easy"
"We could call it LUNCHCOIN!"

And a quick google search brought me here. 

Thanks zecixx

**Comment by technion** [comment]
Hi,

It's completely developed as far as a research project goes. Since I didn't make millions on an ICO (which would be quite humerous as there is 0 business model) I don't have the funds to run nodes 24x7. 

Also like the majority of these projects, there are blockchain components not implemented. There's no proof of work. This would be easy to fix but then would require ongoing nodes and I'll refer to the above point.

I do plan on keeping it operational as libraries update, etc.
